import groovy.transform.Field

pluginManagement {
    private static final @Field String FORGEDEV_VERSION = '7.0.0-beta.51'

    if (new File('forgedev/settings.gradle').exists()) {
        includeBuild 'forgedev'
    } else {
        resolutionStrategy.eachPlugin {
            // TODO [ForgeDev] Consolidate these entry-points
            switch (requested.id.id) {
                case 'net.minecraftforge.forgedev':
                case 'net.minecraftforge.forge.build.convention':
                    useVersion(FORGEDEV_VERSION)
                    break
            }
        }
    }

    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.minecraftforge.net/' }
        //mavenLocal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'forge'

include 'fmlloader'
include 'fmlcore'
include 'mclanguage'
include 'javafmllanguage'
include 'lowcodelanguage'
include 'fmlearlydisplay'
include 'forge-transformers'

enableFeaturePreview 'TYPESAFE_PROJECT_ACCESSORS'

gradle.beforeProject { Project project ->
    project.pluginManager.withPlugin('net.minecraftforge.forge.build.convention') {
        // NOTE: We are defining these variables in here so that the projects can stay isolated, increasing build time.
        // See minecraft.versions.toml for the versions where you can change these values.
        //@formatter:off
        project.ext.javaVersion          = project.gradleutils.unpack(project.bootLibs.versions.java)
        project.ext.minecraftVersion     = project.gradleutils.unpack(project.bootLibs.versions.minecraft)
        project.version                  = project.gitversion.getMCTagOffsetBranch(project.ext.minecraftVersion)
        project.ext.forgeVersion         = project.version.substring(project.ext.minecraftVersion.length() + 1)
        project.ext.minecraftNextVersion = project.gradleutils.unpack(project.bootLibs.versions.minecraft.next)
        project.ext.mcpVersion           = project.gradleutils.unpack(project.bootLibs.versions.mcp)
        project.ext.changelogBase        = project.gradleutils.unpack(project.bootLibs.versions.changelog.base)
        //@formatter:on
    }

    // NOTE: We are adding dependencies to projects instead of through settings, so we don't have to apply forgedev in settings.
    // Applying forgedev in settings will break IDE linting support, which makes it very hard to work with.
    // We can reconsider this if/when switching to Kotlin DSL, or if JetBrains gets their shit together.
    project.repositories {
        // Libraries has to be before maven central because Mojang hosts a classifer that central doesn't (org.lwjgl:lwjgl-freetype:3.3.3:natives-macos-patch)
        maven { url = 'https://libraries.minecraft.net/' }
        mavenCentral()

        project.pluginManager.withPlugin('net.minecraftforge.gradleutils') {
            maven project.gradleutils.forgeMaven
        }

        project.pluginManager.withPlugin('net.minecraftforge.forgedev') {
            maven project.forgedev.mavenizer
        }

        mavenLocal()
    }
}

dependencyResolutionManagement.versionCatalogs {
    // Contains Java, Minecraft, and MCP versions
    register('bootLibs') {
        description = 'Important version numbers that are externally declared for easy modification.'
        from(files('minecraft.versions.toml'))
    }

    register('buildLibs') {
        description = 'Libraries used solely during the build and publish process.'
        from(files('gradle/buildLibs.versions.toml'))
    }

    //@formatter:off
    register('libs') {
        description = 'Libraries used by Forge and its subprojects.'
    }

    register('earlyDisplayLibs') {
        version 'slf4j', '1.8.0-beta4'
        library 'slf4j-api',   'org.slf4j', 'slf4j-api'   versionRef 'slf4j'
        library 'slf4j-jdk14', 'org.slf4j', 'slf4j-jdk14' versionRef 'slf4j'
    }

    register('earlyDisplayTestLibs') {
        library 'powermock-core', 'org.powermock', 'powermock-core' version '2.0.9'

        library 'lwjgl',        'org.lwjgl', 'lwjgl'        withoutVersion()
        library 'lwjgl-glfw',   'org.lwjgl', 'lwjgl-glfw'   withoutVersion()
        library 'lwjgl-opengl', 'org.lwjgl', 'lwjgl-opengl' withoutVersion()
        library 'lwjgl-stb',    'org.lwjgl', 'lwjgl-stb'    withoutVersion()
        bundle  'lwjgl', ['lwjgl', 'lwjgl-glfw', 'lwjgl-opengl', 'lwjgl-stb']
    }
    //@formatter:on
}
